test windows nodes: windows.g5.4xlarge.nvidia.gpu

diff --git a/.github/workflows/release-wheel-windows.yml b/.github/workflows/release-wheel-windows.yml
--- a/.github/workflows/release-wheel-windows.yml
+++ b/.github/workflows/release-wheel-windows.yml
@@ -126,86 +126,89 @@ jobs:
           source "${BUILD_ENV_FILE}"
           # shellcheck disable=SC2086
           ${CONDA_RUN} ${PIP_INSTALL_TORCH}
-      - name: Run Pre-Script with Caching
-        if: ${{ inputs.pre-script != '' }}
-        uses: ./test-infra/.github/actions/run-script-with-cache
-        with:
-          cache-path: ${{ inputs.cache-path }}
-          cache-key: ${{ inputs.cache-key }}
-          repository: ${{ inputs.repository  }}
-          script: ${{ inputs.pre-script }}
-          is_windows: 'enabled'
-      - name: Build clean
-        working-directory: ${{ inputs.repository }}
-        run: |
-          source "${BUILD_ENV_FILE}"
-          ${CONDA_RUN} python setup.py clean
-      - name: Build the wheel (bdist_wheel)
-        working-directory: ${{ inputs.repository }}
-        env:
-          ENV_SCRIPT: ${{ inputs.env-script }}
-          BUILD_PARAMS: ${{ inputs.wheel-build-params }}
-        run: |
           set -x
-          source "${BUILD_ENV_FILE}"
+          DEVICE_PROPERTIES=$(python -c "import torch; print(torch.cuda.get_device_properties(0))")
+          echo DEVICE_PROPERTIES=$DEVICE_PROPERTIES
+      # - name: Run Pre-Script with Caching
+      #   if: ${{ inputs.pre-script != '' }}
+      #   uses: ./test-infra/.github/actions/run-script-with-cache
+      #   with:
+      #     cache-path: ${{ inputs.cache-path }}
+      #     cache-key: ${{ inputs.cache-key }}
+      #     repository: ${{ inputs.repository  }}
+      #     script: ${{ inputs.pre-script }}
+      #     is_windows: 'enabled'
+      # - name: Build clean
+      #   working-directory: ${{ inputs.repository }}
+      #   run: |
+      #     source "${BUILD_ENV_FILE}"
+      #     ${CONDA_RUN} python setup.py clean
+      # - name: Build the wheel (bdist_wheel)
+      #   working-directory: ${{ inputs.repository }}
+      #   env:
+      #     ENV_SCRIPT: ${{ inputs.env-script }}
+      #     BUILD_PARAMS: ${{ inputs.wheel-build-params }}
+      #   run: |
+      #     set -x
+      #     source "${BUILD_ENV_FILE}"
 
-          if [[ "$CU_VERSION" == "cpu" ]]; then
-          # CUDA and CPU are ABI compatible on the CPU-only parts, so strip
-          # in this case
-            export PYTORCH_VERSION="$(${CONDA_RUN} pip show torch | grep ^Version: | sed 's/Version:  *//' | sed 's/+.\+//')"
-          else
-            export PYTORCH_VERSION="$(${CONDA_RUN} pip show torch | grep ^Version: | sed 's/Version:  *//')"
-          fi
+      #     if [[ "$CU_VERSION" == "cpu" ]]; then
+      #     # CUDA and CPU are ABI compatible on the CPU-only parts, so strip
+      #     # in this case
+      #       export PYTORCH_VERSION="$(${CONDA_RUN} pip show torch | grep ^Version: | sed 's/Version:  *//' | sed 's/+.\+//')"
+      #     else
+      #       export PYTORCH_VERSION="$(${CONDA_RUN} pip show torch | grep ^Version: | sed 's/Version:  *//')"
+      #     fi
 
-          # BUILD_VERSION example: 2.4.0+cu121, we don't want the +cu121 part, so remove +cu121
-          BUILD_VERSION=${BUILD_VERSION%+*}
+      #     # BUILD_VERSION example: 2.4.0+cu121, we don't want the +cu121 part, so remove +cu121
+      #     BUILD_VERSION=${BUILD_VERSION%+*}
 
-          if [[ -z "${ENV_SCRIPT}" ]]; then
-            ${CONDA_RUN} python setup.py bdist_wheel
-          else
-            if [[ ! -f ${ENV_SCRIPT} ]]; then
-              echo "::error::Specified env-script file (${ENV_SCRIPT}) not found"
-              exit 1
-            else
-              ${CONDA_RUN} ${ENV_SCRIPT} python setup.py bdist_wheel ${BUILD_PARAMS}
-            fi
-          fi
-      - name: Run post-script
-        working-directory: ${{ inputs.repository }}
-        env:
-          POST_SCRIPT: ${{ inputs.post-script }}
-          ENV_SCRIPT: ${{ inputs.env-script }}
-        if: ${{ inputs.post-script != '' }}
-        run: |
-          set -euxo pipefail
-          source "${BUILD_ENV_FILE}"
-          ${CONDA_RUN} ${ENV_SCRIPT} ${POST_SCRIPT}
-      - name: Smoke Test
-        env:
-          PACKAGE_NAME: ${{ inputs.package-name }}
-          SMOKE_TEST_SCRIPT: ${{ inputs.smoke-test-script }}
-        run: |
-          source "${BUILD_ENV_FILE}"
-          WHEEL_NAME=$(ls "${{ inputs.repository }}/dist/")
-          echo "$WHEEL_NAME"
-          ${CONDA_RUN} pip install "${{ inputs.repository }}/dist/$WHEEL_NAME"
-          if [[ ! -f "${{ inputs.repository }}"/${SMOKE_TEST_SCRIPT} ]]; then
-            echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} not found"
-            ${CONDA_RUN} python -c "import ${PACKAGE_NAME}; print('package version is ', ${PACKAGE_NAME}.__version__)"
-          else
-            echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} found"
-            ${CONDA_RUN} python "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT}"
-          fi
-      # NB: Only upload to GitHub after passing smoke tests
-      - name: Upload wheel to GitHub
-        continue-on-error: true
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ env.ARTIFACT_NAME }}
-          path: ${{ inputs.repository }}/dist/
-      - uses: ./test-infra/.github/actions/teardown-windows
-        if: always()
-        name: Teardown Windows
+      #     if [[ -z "${ENV_SCRIPT}" ]]; then
+      #       ${CONDA_RUN} python setup.py bdist_wheel
+      #     else
+      #       if [[ ! -f ${ENV_SCRIPT} ]]; then
+      #         echo "::error::Specified env-script file (${ENV_SCRIPT}) not found"
+      #         exit 1
+      #       else
+      #         ${CONDA_RUN} ${ENV_SCRIPT} python setup.py bdist_wheel ${BUILD_PARAMS}
+      #       fi
+      #     fi
+      # - name: Run post-script
+      #   working-directory: ${{ inputs.repository }}
+      #   env:
+      #     POST_SCRIPT: ${{ inputs.post-script }}
+      #     ENV_SCRIPT: ${{ inputs.env-script }}
+      #   if: ${{ inputs.post-script != '' }}
+      #   run: |
+      #     set -euxo pipefail
+      #     source "${BUILD_ENV_FILE}"
+      #     ${CONDA_RUN} ${ENV_SCRIPT} ${POST_SCRIPT}
+      # - name: Smoke Test
+      #   env:
+      #     PACKAGE_NAME: ${{ inputs.package-name }}
+      #     SMOKE_TEST_SCRIPT: ${{ inputs.smoke-test-script }}
+      #   run: |
+      #     source "${BUILD_ENV_FILE}"
+      #     WHEEL_NAME=$(ls "${{ inputs.repository }}/dist/")
+      #     echo "$WHEEL_NAME"
+      #     ${CONDA_RUN} pip install "${{ inputs.repository }}/dist/$WHEEL_NAME"
+      #     if [[ ! -f "${{ inputs.repository }}"/${SMOKE_TEST_SCRIPT} ]]; then
+      #       echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} not found"
+      #       ${CONDA_RUN} python -c "import ${PACKAGE_NAME}; print('package version is ', ${PACKAGE_NAME}.__version__)"
+      #     else
+      #       echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} found"
+      #       ${CONDA_RUN} python "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT}"
+      #     fi
+      # # NB: Only upload to GitHub after passing smoke tests
+      # - name: Upload wheel to GitHub
+      #   continue-on-error: true
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: ${{ env.ARTIFACT_NAME }}
+      #     path: ${{ inputs.repository }}/dist/
+      # - uses: ./test-infra/.github/actions/teardown-windows
+      #   if: always()
+      #   name: Teardown Windows
 
 
 concurrency:
